version: 2

models:
  - name: silver_yellow_tripdata
    description: "Cleaned and incremental yellow taxi trip data."
    columns:
      - name: unique_trip_id
        description: "Primary key generated via MD5 hash of trip attributes."
        tests:
          - unique
          - not_null

      - name: tpep_pickup_datetime
        tests:
          - not_null

      - name: payment_type
        tests:
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5, 6]
              quote: false

      - name: vendorid
        tests:
          - relationships:
              to: source('nyc_taxi', 'yellow_tripdata')
              field: VendorID
             