nyc_taxi:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PG_HOST', 'postgrest') }}"
      user: "{{ env_var('PG_USER', 'airflow') }}"
      pass: "{{ env_var('PG_PASS', 'airflow12') }}"
      dbname: "{{ env_var('PG_DB', 'airflow_db') }}"
      schema: "{{ env_var('PG_SCHEMA', 'public') }}"
      port: 5432
      threads: 4

    ci:
        type: postgres
        host: "{{ env_var('POSTGRES_HOST') }}"
        user: "{{ env_var('POSTGRES_USER') }}"
        password: "{{ env_var('POSTGRES_PASSWORD') }}"
        port: "{{ env_var('POSTGRES_PORT') | as_number }}"
        dbname: "{{ env_var('POSTGRES_DB') }}"
        schema: public
        threads: 4